stages:
  preprocess:
    cmd: python3 src/preprocess.py --input data/raw/iris.csv --output data/preprocessed/iris_processed.csv --add-noise
    deps:
      - src/preprocess.py
      - data/raw/iris.csv
    outs:
      - data/preprocessed/iris_processed.csv

  train:
    cmd: python3 src/train.py --input data/preprocessed/iris_processed.csv --model model.pkl
    deps:
      - src/train.py
      - data/preprocessed/iris_processed.csv
    outs:
      - model.pkl
    params:
      - train.model_params.max_iter

  evaluate:
    cmd: python3 src/evaluate.py --input data/preprocessed/iris_processed.csv --model model.pkl --metrics metrics.json
    deps:
      - src/evaluate.py
      - data/preprocessed/iris_processed.csv
      - model.pkl
    metrics:
      - metrics.json:
          cache: false
      - metrics.yaml:
          cache: false